FROM ubuntu:18.04

RUN apt-get update --fix-missing

COPY Xilinx_Unified_2020.1_0602_1208_Lin64.bin /tmp/
COPY auth.sh /tmp/

RUN /tmp/Xilinx_Unified_2020.1_0602_1208_Lin64.bin --keep --noexec --target /tmp/wi
