FROM ubuntu:18.04

ARG USER_ID
ARG GROUP_ID
ARG VIVADO_BIN

RUN apt-get update --fix-missing

COPY ${VIVADO_BIN} /tmp/
COPY auth.sh /tmp/

RUN /tmp/${VIVADO_BIN} --keep --noexec --target /tmp/wi

RUN addgroup --gid ${GROUP_ID} user
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} --gid ${GROUP_ID} user
USER user
